apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shobteeprajump-client
  name: shobteeprajump-client-deployment
  namespace: group-4
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shobteeprajump-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shobteeprajump-client
    spec:
      containers:
      - env:
        - name: VITE_API_URL
          value: https://tcc-01.th1.proen.cloud
        image: justtod/shobteeprajump-client:v0.5.15
        imagePullPolicy: Always
        name: shobteeprajump-client
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30