apiVersion: apps/v1
kind: Deployment
metadata:
  name: shobteeprajump-deployment
  namespace: group-4
  labels:
    app: shobteeprajump-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shobteeprajump-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shobteeprajump-app
    spec:
      containers:
      - name: shobteeprajump-app
        image: diskette42/app
        env:
          - name: DATABASE_URL
            value: mysql://user:user@group4-mysql.group-4:3306/stockdb
          - name: PORT
            value: "3000"
          - name: RABBITMQ_SVC
            value: group4-rabbitmq.group-4:5672
          - name: CONSUME_CHECKOUT_SVC
            value: group4-rabbitmq2.group-4:5673
        ports:
          - containerPort: 3000
        resources: {}
status: {}